/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MitraMenu;

import javax.swing.JPanel;
import kasirfrontend.KasirPaymentPage;

/**
 *
 * @author Lenovo
 */
public class Mitra extends javax.swing.JFrame {

    /**
     * Creates new form Mitra
     */
    
    PanelTour pt;
    PanelSupplier ps;
    PanelCashier pc;
    
    public Mitra() {
        initComponents();
         setLocationRelativeTo(null);
        

        pt = new PanelTour();
        ps = new PanelSupplier();
        pc = new PanelCashier();
       
        
        
        PanelMitraBox.add(pt);
        PanelMitraBox.add(ps);
        PanelMitraBox.add(pc);
     
        
        pt.setVisible(false);
        ps.setVisible(false);
        pc.setVisible(false);
        
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonTourMitra = new javax.swing.JButton();
        ButtonSupplierMitra = new javax.swing.JButton();
        DashboardReverseBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonCashierMitra = new javax.swing.JButton();
        PanelMitraBox = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(660, 340));

        jPanel1.setBackground(new java.awt.Color(200, 191, 173));

        ButtonTourMitra.setText("Tour");
        ButtonTourMitra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonTourMitraMousePressed(evt);
            }
        });
        ButtonTourMitra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTourMitraActionPerformed(evt);
            }
        });

        ButtonSupplierMitra.setText("Supplier");
        ButtonSupplierMitra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonSupplierMitraMousePressed(evt);
            }
        });
        ButtonSupplierMitra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSupplierMitraActionPerformed(evt);
            }
        });

        DashboardReverseBtn.setPreferredSize(new java.awt.Dimension(20, 20));
        DashboardReverseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardReverseBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Dashboard >");

        jLabel2.setText("Mitra");

        ButtonCashierMitra.setText("Cashier");
        ButtonCashierMitra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonCashierMitraMousePressed(evt);
            }
        });
        ButtonCashierMitra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCashierMitraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonTourMitra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonSupplierMitra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonCashierMitra))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DashboardReverseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(425, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DashboardReverseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonTourMitra)
                    .addComponent(ButtonSupplierMitra)
                    .addComponent(ButtonCashierMitra))
                .addContainerGap())
        );

        PanelMitraBox.setBackground(new java.awt.Color(217, 217, 217));
        PanelMitraBox.setPreferredSize(new java.awt.Dimension(660, 340));
        PanelMitraBox.setLayout(new javax.swing.BoxLayout(PanelMitraBox, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelMitraBox, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelMitraBox, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSupplierMitraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSupplierMitraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSupplierMitraActionPerformed

    private void ButtonTourMitraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTourMitraActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_ButtonTourMitraActionPerformed

    private void ButtonTourMitraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonTourMitraMousePressed
        pt.setVisible(true);
        ps.setVisible(false);
        pc.setVisible(false);
     
       // TODO add your handling code here:
    }//GEN-LAST:event_ButtonTourMitraMousePressed

    private void ButtonSupplierMitraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSupplierMitraMousePressed
        pt.setVisible(false);
        ps.setVisible(true);
        pc.setVisible(false);  
     
        
         //TODO add your handling code here:
    }//GEN-LAST:event_ButtonSupplierMitraMousePressed

    private void ButtonCashierMitraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCashierMitraMousePressed
        pt.setVisible(false);
        ps.setVisible(false);
        pc.setVisible(true); 
      
       // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCashierMitraMousePressed

    private void ButtonCashierMitraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCashierMitraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCashierMitraActionPerformed

    private void DashboardReverseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardReverseBtnActionPerformed
        DsbSAdmin dsbSAdminFrame = new DsbSAdmin();
    
    // Menampilkan frame DsbSAdmin
    dsbSAdminFrame.setVisible(true);
    
    // Menutup frame Mitra
    dispose();
    }//GEN-LAST:event_DashboardReverseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mitra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mitra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mitra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mitra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mitra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCashierMitra;
    private javax.swing.JButton ButtonSupplierMitra;
    private javax.swing.JButton ButtonTourMitra;
    private javax.swing.JButton DashboardReverseBtn;
    private javax.swing.JPanel PanelMitraBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
