/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.MitraMenu;

/**
 *
 * @author Lenovo
 */
public class PanelTour extends javax.swing.JPanel {

    private Mitra PanelMitraBox; // Menyimpan referensi ke frame utama Mitra
    
    public PanelTour(Mitra mitraFrame) {
    initComponents();
    this.PanelMitraBox = mitraFrame; // Inisialisasi variabel PanelMitraBox dengan objek Mitra
}


   PanelTour() {
    initComponents(); // Panggil metode initComponents() untuk menginisialisasi komponen
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableMitraTour = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        btnSearchTour = new javax.swing.JButton();
        btnAddTour = new javax.swing.JButton();

        setBackground(new java.awt.Color(217, 217, 217));

        TableMitraTour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "tour_id", "Name", "Address", "Telephone", "Invoice Tour", "Action"
            }
        ));
        jScrollPane1.setViewportView(TableMitraTour);

        btnSearchTour.setText("Search");
        btnSearchTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTourActionPerformed(evt);
            }
        });

        btnAddTour.setText("Add Tour");
        btnAddTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAddTourMousePressed(evt);
            }
        });
        btnAddTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddTour, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchTour)
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchTour)
                    .addComponent(btnAddTour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTourActionPerformed
    AddTour addTour = new AddTour();
    addTour.setVisible(true);
    }//GEN-LAST:event_btnAddTourActionPerformed

    private void btnAddTourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddTourMousePressed
if (PanelMitraBox != null) {
    PanelMitraBox.panelCashier.setVisible(false);
    PanelMitraBox.panelSupplier.setVisible(false);
    PanelMitraBox.panelTour.setVisible(false);
} else {
    System.err.println("PanelMitraBox belum diinisialisasi!");
}

    }//GEN-LAST:event_btnAddTourMousePressed

    private void btnSearchTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchTourActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableMitraTour;
    private javax.swing.JButton btnAddTour;
    private javax.swing.JButton btnSearchTour;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private PanelTour(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
