/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.superkasirfrontend;

import dtos.UniverseResponse;
import dtos.purchase.CreatePurchaseDTO;
import dtos.purchase.ProductDTOs;
import dtos.purchase.product.ExistingProductRequest;
import dtos.purchase.product.NewProductRequest;
import dtos.supplier.Supplier;
import dtos.supplier.SupplierDTOs;
import helpers.Helpers;
import helpers.Message;
import views.MitraMenu.Mitra;
import web.Http;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Rosemary
 */
public class Purchase extends javax.swing.JFrame {

    private ProductDTOs productDTOs;
    private SupplierDTOs supplierDTOs;
    private List<NewProductRequest> newProductList;
    private List<ExistingProductRequest> existingProductList;
    private DefaultTableModel listRows;
    private int index = 1;

    /**
     * Creates new form Purchase
     */
    public Purchase() {
        initComponents();
        tabAddProduct.setVisible(false);
        newProductList = new ArrayList<>();
        existingProductList = new ArrayList<>();

        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setSelectionSuppliers();
        setSelectionProducts();

        String[] fields = new String[]{
                "No", "Barcode", "Nama Barang", "Harga Beli", "Harga Jual", "Profit Sharing Amount", "Quantity"
        };
        listRows = new DefaultTableModel(null, fields);
        TabelPurchase.setModel(listRows);
    }

    private void setSelectionSuppliers() {
        Http http = new Http();
        this.supplierDTOs = http.sendGetRequest("suppliers/all", SupplierDTOs.class);

        if(supplierDTOs.getData() == null){
            return;
        }
        
        for (Supplier supplier : supplierDTOs.getData()) {
            CmboboxSupName.addItem(supplier.getName());
        }
    }

    private void setSelectionProducts() {
        Http http = new Http();
        this.productDTOs = http.sendGetRequest("products/all", ProductDTOs.class);

        if(productDTOs.getData() == null){
            return;
        }
        
        for (dtos.product.Product product : productDTOs.getData()) {
            existingProductId.addItem(String.valueOf(product));
        }
    }

    private void addNewProductToTable(NewProductRequest product) {
        listRows.addRow(new Object[]{
                index++,
                product.getBarcode(),
                product.getName(),
                product.getPriceBuy(),
                product.getPriceSell(),
                product.getProfitSharingAmount(),
                product.getQuantity()
        });
    }

    private void addExistingProductToTable(ExistingProductRequest inputExisting, dtos.product.Product product) {
        listRows.addRow(new Object[]{
                index++,
                product.getBarcode(),
                product.getName(),
                inputExisting.getPriceBuy(),
                inputExisting.getPriceSell(),
                inputExisting.getProfitSharingAmount(),
                inputExisting.getQuantity()
        });
    }

    public String getBarcodeSelectedTable() {
        int row = TabelPurchase.getSelectedRow();
        if (row == -1) {
            Message.error("Pilih baris yang ingin dihapus dulu", "Error");
            return null;
        }
        return (String) TabelPurchase.getValueAt(row, 1);
    }

    private void observerAddProduct(Long price, int quantity) {
        int totalProduct = Helpers.convertToInt(inputTotalProduct.getText());
        inputTotalProduct.setText(String.valueOf(totalProduct + 1));

        Long totalPrice = Helpers.convertToLong(inputTotalPrice.getText());
        inputTotalPrice.setText(String.valueOf(totalPrice + (price * quantity)));
    }

    private void observerDeleteProduct(Long price, int quantity) {
        int totalProduct = Helpers.convertToInt(inputTotalProduct.getText());
        inputTotalProduct.setText(String.valueOf(totalProduct - 1));

        Long totalPrice = Helpers.convertToLong(inputTotalPrice.getText());
        inputTotalPrice.setText(String.valueOf(totalPrice - price));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPurchase = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        labelSuplierName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CmboboxSupName = new javax.swing.JComboBox<>();
        btnNewPurchase = new javax.swing.JButton();
        btnExisting = new javax.swing.JButton();
        inputTotalProduct = new javax.swing.JTextField();
        inputTotalPrice = new javax.swing.JTextField();
        inputAmount = new javax.swing.JTextField();
        inputRefund = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnCancelPurc = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        tabAddProduct = new javax.swing.JTabbedPane();
        PanelNewProduct = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TFBarcode = new javax.swing.JTextField();
        TFName = new javax.swing.JTextField();
        TFPriceBuy = new javax.swing.JTextField();
        TFPriceSell = new javax.swing.JTextField();
        TFQuantity = new javax.swing.JTextField();
        TFProfitSAmon = new javax.swing.JTextField();
        btnAddProdNew = new javax.swing.JButton();
        btnCancelNew = new javax.swing.JButton();
        PanelNewProduct1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        existingInputName = new javax.swing.JTextField();
        existingInputPriceBuy = new javax.swing.JTextField();
        existingInputSell = new javax.swing.JTextField();
        existingInputQuantity = new javax.swing.JTextField();
        existingInputProfitSharingAmount = new javax.swing.JTextField();
        btnAddProdExisting = new javax.swing.JButton();
        btnCancelNew2 = new javax.swing.JButton();
        tfExistingPriceSellinp = new javax.swing.JTextField();
        existingInputBarcode1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        existingProductId = new javax.swing.JComboBox<>();
        btnDel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabelPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Barcode", "Nama Barang", "Harga Beli", "Harga Jual", "Profit Sharing Amount", "Stok"
            }
        ));
        jScrollPane1.setViewportView(TabelPurchase);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        labelSuplierName.setText("Supplier Name");

        jLabel2.setText("Add Product");

        jLabel3.setText("Total Product");

        jLabel4.setText("Total Price");

        jLabel5.setText("Amount");

        jLabel6.setText("Refund");

        btnNewPurchase.setText("New");
        btnNewPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPurchaseActionPerformed(evt);
            }
        });

        btnExisting.setText("Existing");
        btnExisting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExistingActionPerformed(evt);
            }
        });

        inputTotalProduct.setEnabled(false);
        inputTotalProduct.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                inputTotalProductCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        inputTotalProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTotalProductActionPerformed(evt);
            }
        });

        inputTotalPrice.setEnabled(false);

        inputAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAmountActionPerformed(evt);
            }
        });

        inputRefund.setEnabled(false);

        jButton3.setBackground(new java.awt.Color(51, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Purchase");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnCancelPurc.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelPurc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelPurc.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelPurc.setText("Cancel");
        btnCancelPurc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelPurcActionPerformed(evt);
            }
        });

        jLabel8.setText("Form Purchase");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButton3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelSuplierName, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnNewPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnExisting))
                                .addComponent(inputTotalPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputRefund, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CmboboxSupName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnCancelPurc))
                            .addComponent(inputTotalProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSuplierName)
                    .addComponent(CmboboxSupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnNewPurchase)
                    .addComponent(btnExisting))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputTotalProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inputRefund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelPurc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Purchase");

        btnBack.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\ImageFolder\\kembali.png"));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tabAddProduct.setEnabled(false);

        PanelNewProduct.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("New Product");

        jLabel9.setText("Barcode");

        jLabel10.setText("Name");

        jLabel11.setText("Price Buy");

        jLabel12.setText("Price Sell");

        jLabel13.setText("Quantity");

        jLabel14.setText("Profit Sharing Amount");

        TFQuantity.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TFQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFQuantityActionPerformed(evt);
            }
        });

        btnAddProdNew.setBackground(new java.awt.Color(102, 204, 255));
        btnAddProdNew.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddProdNew.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProdNew.setText("Add");
        btnAddProdNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdNewActionPerformed(evt);
            }
        });

        btnCancelNew.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelNew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelNew.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelNew.setText("Cancel");
        btnCancelNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNewProductLayout = new javax.swing.GroupLayout(PanelNewProduct);
        PanelNewProduct.setLayout(PanelNewProductLayout);
        PanelNewProductLayout.setHorizontalGroup(
            PanelNewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNewProductLayout.createSequentialGroup()
                .addGroup(PanelNewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNewProductLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelNewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelNewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFBarcode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TFName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TFPriceBuy, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TFPriceSell, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TFQuantity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TFProfitSAmon, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(PanelNewProductLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnAddProdNew, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelNew)
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelNewProductLayout.setVerticalGroup(
            PanelNewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNewProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(PanelNewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TFBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelNewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelNewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TFPriceBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelNewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TFPriceSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelNewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TFQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelNewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TFProfitSAmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelNewProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddProdNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabAddProduct.addTab("New", PanelNewProduct);

        PanelNewProduct1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Existing Product");

        jLabel23.setText("Select Product");

        jLabel24.setText("Name");

        jLabel25.setText("Price Buy");

        jLabel26.setText("Price Sell");

        jLabel27.setText("Quantity");

        jLabel28.setText("Profit Sharing Amount");

        existingInputName.setEnabled(false);

        existingInputQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingInputQuantityActionPerformed(evt);
            }
        });

        btnAddProdExisting.setBackground(new java.awt.Color(102, 204, 255));
        btnAddProdExisting.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddProdExisting.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProdExisting.setText("Add");
        btnAddProdExisting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProdExistingActionPerformed(evt);
            }
        });

        btnCancelNew2.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelNew2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelNew2.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelNew2.setText("Cancel");
        btnCancelNew2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelNew2ActionPerformed(evt);
            }
        });

        existingInputBarcode1.setEnabled(false);

        jLabel29.setText("Barcode");

        existingProductId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingProductIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNewProduct1Layout = new javax.swing.GroupLayout(PanelNewProduct1);
        PanelNewProduct1.setLayout(PanelNewProduct1Layout);
        PanelNewProduct1Layout.setHorizontalGroup(
            PanelNewProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNewProduct1Layout.createSequentialGroup()
                .addGroup(PanelNewProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNewProduct1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelNewProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelNewProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(existingInputName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(existingInputPriceBuy, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(existingInputQuantity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(existingInputProfitSharingAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(existingInputBarcode1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelNewProduct1Layout.createSequentialGroup()
                                .addGroup(PanelNewProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelNewProduct1Layout.createSequentialGroup()
                                        .addComponent(existingInputSell, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfExistingPriceSellinp, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(existingProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PanelNewProduct1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnAddProdExisting, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelNew2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelNewProduct1Layout.setVerticalGroup(
            PanelNewProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNewProduct1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(24, 24, 24)
                .addGroup(PanelNewProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(existingProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelNewProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(existingInputBarcode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelNewProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(existingInputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelNewProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(existingInputPriceBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(PanelNewProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(existingInputSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfExistingPriceSellinp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PanelNewProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(existingInputQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelNewProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(existingInputProfitSharingAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelNewProduct1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelNew2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddProdExisting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabAddProduct.addTab("Existing", PanelNewProduct1);

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tabAddProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDel)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelPurcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelPurcActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
    }//GEN-LAST:event_btnCancelPurcActionPerformed

    private void inputTotalProductCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_inputTotalProductCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTotalProductCaretPositionChanged

    private void btnExistingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExistingActionPerformed
        // TODO add your handling code here:
        tabAddProduct.setVisible(true);
        tabAddProduct.setSelectedIndex(1);
    }//GEN-LAST:event_btnExistingActionPerformed

    private void btnNewPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPurchaseActionPerformed
        // TODO add your handling code here:
        tabAddProduct.setVisible(true);
        tabAddProduct.setSelectedIndex(0);
    }//GEN-LAST:event_btnNewPurchaseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //button for back to Product file
        this.setVisible(false);
        this.dispose();
        Product ProductFrame = new Product();
        ProductFrame.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCancelNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelNewActionPerformed
        // TODO add your handling code here:
        tabAddProduct.setVisible(false);

    }//GEN-LAST:event_btnCancelNewActionPerformed

    private void btnCancelNew2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelNew2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelNew2ActionPerformed

    private void existingProductIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_existingProductIdItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_existingProductIdItemStateChanged

    private void existingProductIdPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_existingProductIdPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_existingProductIdPropertyChange

    private void existingInputQuantityActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void btnAddProdExistingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdExistingActionPerformed
        // TODO add your handling code here:
        int indexSelectedProductId = existingProductId.getSelectedIndex();
        var productSelected = productDTOs.getData().get(indexSelectedProductId);

        ExistingProductRequest product = new ExistingProductRequest(
                productSelected.getProductId(),
                Helpers.convertToLong(existingInputPriceBuy.getText()),
                Helpers.convertToLong(existingInputSell.getText()),
                Helpers.convertToInt(existingInputQuantity.getText()),
                Helpers.convertToLong(existingInputProfitSharingAmount.getText())
        );

        addExistingProductToTable(product, productSelected);
        existingProductList.add(product);
        observerAddProduct(product.getPriceBuy(), product.getQuantity());
    }//GEN-LAST:event_btnAddProdExistingActionPerformed

    private void btnAddProdNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProdNewActionPerformed
        // TODO add your handling code here:
        NewProductRequest product = new NewProductRequest(
                TFBarcode.getText(),
                TFName.getText(),
                "", // TODO: add field for brand
                Helpers.convertToLong(TFPriceBuy.getText()),
                Helpers.convertToLong(TFPriceSell.getText()),
                Helpers.convertToInt(TFQuantity.getText()),
                Helpers.convertToLong(TFProfitSAmon.getText())
        );

        addNewProductToTable(product);
        newProductList.add(product);
        observerAddProduct(product.getPriceBuy(), product.getQuantity());
    }//GEN-LAST:event_btnAddProdNewActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        String barcode = getBarcodeSelectedTable();
        if (barcode == null) {
            return;
        }
//        if (Message.confirm("Yakin ingin menghapus data ini?", "Confirm") != 0) {
//            return;
//        }

        // TODO: I think this is a bug, even though the tables have the same barcode. It will be a problem when it is removed.
        // I think the best practice is that barcodes should not have duplicates when adding products
        for (int i = 0; i < newProductList.size(); i++) {
            NewProductRequest product = newProductList.get(i);
            if (product.getBarcode().equals(barcode)) {
                observerDeleteProduct(product.getPriceBuy(), product.getQuantity());
                newProductList.remove(i);
                listRows.removeRow(TabelPurchase.getSelectedRow());
            }
        }
        for (int i = 0; i < existingProductList.size(); i++) {
            int index = i;
            productDTOs.getData().stream().filter((product) -> (product.getBarcode().equals(barcode))).forEachOrdered((product) -> {
                observerDeleteProduct(existingProductList.get(index).getPriceBuy(), existingProductList.get(index).getQuantity());
                existingProductList.remove(index);
                listRows.removeRow(TabelPurchase.getSelectedRow());
            });
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelActionPerformed

    private void existingProductIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingProductIdActionPerformed
        int indexSelectedProductId = existingProductId.getSelectedIndex();
        var productSelected = productDTOs.getData().get(indexSelectedProductId);
        existingInputBarcode1.setText(productSelected.getBarcode());
        existingInputName.setText(productSelected.getName());
        // TODO add your handling code here:
    }//GEN-LAST:event_existingProductIdActionPerformed

    private void inputAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAmountActionPerformed
        Long totalPrice = Helpers.convertToLong(inputTotalPrice.getText());
        Long amount = Helpers.convertToLong(inputAmount.getText());
        Long result = totalPrice - amount;
        inputRefund.setText(String.valueOf(result));
    }//GEN-LAST:event_inputAmountActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int indexSelectedSupplierId = CmboboxSupName.getSelectedIndex();
        var supplierSelected = supplierDTOs.getData().get(indexSelectedSupplierId);

        Long amount = Helpers.convertToLong(inputAmount.getText());
        Long totalPrice = Helpers.convertToLong(inputTotalPrice.getText());
        if (amount <= totalPrice) {
            Message.error("Amount must be greater or equals than total price", "Error");
            return;
        }

        if (Message.confirm("Are you sure to purchase this product?", "Confirm") != 0) {
            return;
        }

        Http http = new Http();
        UniverseResponse response = http.post("admin/purchases", new CreatePurchaseDTO(
                supplierSelected.getSupplierId(),
                Helpers.convertToLong(inputAmount.getText()),
                newProductList,
                existingProductList
        ), UniverseResponse.class);

        if (http.isSuccess()) {
            this.dispose();
            (new Product()).setVisible(true);
        } else {
            Message.errors(response.errors);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void TFQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFQuantityActionPerformed

    private void inputTotalProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTotalProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTotalProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmboboxSupName;
    private javax.swing.JPanel PanelNewProduct;
    private javax.swing.JPanel PanelNewProduct1;
    private javax.swing.JTextField TFBarcode;
    private javax.swing.JTextField TFName;
    private javax.swing.JTextField TFPriceBuy;
    private javax.swing.JTextField TFPriceSell;
    private javax.swing.JTextField TFProfitSAmon;
    private javax.swing.JTextField TFQuantity;
    private javax.swing.JTable TabelPurchase;
    private javax.swing.JButton btnAddProdExisting;
    private javax.swing.JButton btnAddProdNew;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancelNew;
    private javax.swing.JButton btnCancelNew2;
    private javax.swing.JButton btnCancelPurc;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnExisting;
    private javax.swing.JButton btnNewPurchase;
    private javax.swing.JTextField existingInputBarcode1;
    private javax.swing.JTextField existingInputName;
    private javax.swing.JTextField existingInputPriceBuy;
    private javax.swing.JTextField existingInputProfitSharingAmount;
    private javax.swing.JTextField existingInputQuantity;
    private javax.swing.JTextField existingInputSell;
    private javax.swing.JComboBox<String> existingProductId;
    private javax.swing.JTextField inputAmount;
    private javax.swing.JTextField inputRefund;
    private javax.swing.JTextField inputTotalPrice;
    private javax.swing.JTextField inputTotalProduct;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelSuplierName;
    private javax.swing.JTabbedPane tabAddProduct;
    private javax.swing.JTextField tfExistingPriceSellinp;
    // End of variables declaration//GEN-END:variables
}
